# Generated by Django 3.0.2 on 2020-03-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_products_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
